services:
  client-react-prod:
    image: coldyx/client-react:latest
    init: true
    depends_on:
      - api-node-prod
      - api-golang-prod
    networks:
      - frontend
    ports:
      - 80:8080

  api-node-prod:
    image: coldyx/api-node:latest
    init: true
    environment:
      - DATABASE_URL=${DATABASE_PROD_URL}
    depends_on:
      - postgres-prod
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000

  api-golang-prod:
    image: coldyx/api-golang:latest
    init: true
    environment:
      - DATABASE_URL=${DATABASE_PROD_URL}
    depends_on:
      - postgres-prod
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080

  postgres-prod:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_PROD_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PROD_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PROD_DB}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - backend

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

volumes:
  pgdata_prod: